name: Catalog Placements Assignment

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make
    
    - name: Build project
      run: make
    
    - name: Run assignment
      run: |
        ./catalog_assignment > assignment_output.txt
        cat assignment_output.txt
    
    - name: Verify output format
      run: |
        if grep -q "Test Case 1 Secret:" assignment_output.txt && grep -q "Test Case 2 Secret:" assignment_output.txt; then
          echo "✅ Output format is correct"
        else
          echo "❌ Output format is incorrect"
          exit 1
        fi
    
    - name: Upload output
      uses: actions/upload-artifact@v3
      with:
        name: assignment-output
        path: assignment_output.txt

  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
    
    - name: Build project
      run: |
        g++ -std=c++17 -Wall -Wextra -O2 -Iinclude -Isrc -o catalog_assignment.exe src/main.cpp
    
    - name: Run assignment
      run: |
        ./catalog_assignment.exe
